name: Deploy to Hetzner Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 91.99.29.182
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www
          if [ -d "hero-belegscanner" ]; then
            cd hero-belegscanner
            git pull
          else
            git clone https://github.com/rolfikill/hero-belegscanner.git
            cd hero-belegscanner
          fi
          
          # Update dependencies
          source document-scanner-env/bin/activate || python3 -m venv document-scanner-env && source document-scanner-env/bin/activate
          pip install -r requirements.txt
          
          # Restart service
          sudo systemctl restart hero-belegscanner || echo "Service not yet configured"
          
          echo "✅ Deployment completed!" 